#!/bin/bash
echo ""
echo "This script will package a set of files."
echo ""

echo "Make sure to copy the files over to /files/ directory.  Use the command 'cp -r --parents /path/to/file files/'"

echo "If not done, please exit out of this program"

echo "What do you want to call the package?"

read payload

tar -czvf $payload.tar.gz ./files
